### ISSUE TITLE
Beaver Builder cache issues

### ISSUE THREAD

**Issue by A5hleyRich** [spinupwp/spinupwp-plugin#1]
SpinupWP page caching does not play well with Beaver Builder.

**Comment by A5hleyRich** [comment]
User reported issue now resolved. Closing.

**Comment by A5hleyRich** [comment]
Another user has reported issues with Beaver Building. Reopening.

**Comment by Pross** [comment]
Simon from Beaver Builder here....

We have an issue open our end to clear spinups cache on layout publish, isnt in a released version yet. Unless you want to add our publish actions to your cache clear actions, up to you?

**Comment by Pross** [comment]
@A5hleyRich ?

**Comment by A5hleyRich** [comment]
Hey @Pross. Which actions would be need to purge the cache on?

**Comment by Pross** [comment]
`fl_builder_cache_cleared`
`fl_builder_after_save_layout`
`fl_builder_after_save_user_template`

**Comment by arvoisa** [comment]
There are still issues.

When you make changes in Beaver Builder, the css and js files are deleted, then they are recreated when the next user visits that page. They are not recreated when you hit the cache clear button.

So, when page cache expires SpinupWP clears cache, it will also trigger cache clear on BB end. But SpinupWP doesnt include new css files, it tries to load old ones instead. That gives us plenty of 404s.

**Comment by BoyetDgte** [comment]
+1 https://secure.helpscout.net/conversation/2246924468/227795?folderId=2447602

> I’m not sure whether the issue is with my spin up config or something else… I had the site on pantheon originally so it may be some leftover code pantheon inserts into the system to deal with their multi-dev environments. It’s not happening on any other sites either.
> 
> The issue is with Assael.com. Beaver builder outputs fresh CSS files and purges the cache on every page load but after a day or so, the cached css and JS files are 404ing. I’ve tried changing the caching settings on both BB and Spinup but it the only thing that cures it temporarily is to purge the cache manually on spin up. Any help or pointers would be greatly appreciate
