### ISSUE TITLE
Option to clear specific post/URL

### ISSUE THREAD

**Issue by gilbitron** [spinupwp/spinupwp-plugin#28]
> Feature request: could you add an option to the WP plugin to clear nginx cache for a certain post/URL like you have it in wp cli

**Comment by cailliewest** [comment]
vote:

>  Page specific level cache clearing - user triggered (good place would be in the SpinUP admin bar when on that specific page)
Cache settings and maintenance inside WP
Exclude rules inside WP
Management for Redis inside WP

https://app.intercom.io/a/apps/yt0wx7wh/inbox/inbox/3033515/conversations/24499582081

**Comment by bradt** [comment]
I find myself updating posts and pages to clear the page cache now and then. For example, to get a new job posting to appear on our [About page](https://deliciousbrains.com/about/#careers), I update the About page.

It would be handy if I could just purge the page cache without having to update the page:

![image](https://user-images.githubusercontent.com/190095/69655219-7da8e100-104c-11ea-9b30-c859294f8d20.png)

![image](https://user-images.githubusercontent.com/190095/69655506-0889db80-104d-11ea-90a8-ada9ef089359.png)

How hard would this be?

**Comment by Jamesclark32** [comment]
Resolved by #73
