### ISSUE TITLE
CLI commands to start/end maintenance mode

### ISSUE THREAD

**Issue by polevaultweb** [spinupwp/spinupwp-plugin#39]
We can then use this in deployment scripts to put the site offline whilst we do the deployments.

To put the site in maintenance mode:
```
// Create maintenance file to signal that we are upgrading.
$maintenance_string = '<?php $upgrading = ' . time() . '; ?>';
$maintenance_file   = $to . '.maintenance';
$wp_filesystem->delete( $maintenance_file );
$wp_filesystem->put_contents( $maintenance_file, $maintenance_string, FS_CHMOD_FILE );
```

To take it off
```
// Remove maintenance file, we're done with potential site-breaking changes.
$wp_filesystem->delete( $maintenance_file );
```

**Comment by polevaultweb** [comment]
@A5hleyRich what do you think? We can call the file `spinupwp.maintenance` so we can call the two commands in different requests

**Comment by A5hleyRich** [comment]
As discussed, we can use the WP-CLI built-in commands for this:

https://developer.wordpress.org/cli/commands/maintenance-mode/
