### ISSUE TITLE
Clear page cache on core/plugin/theme upgrade

### ISSUE THREAD

**Issue by gilbitron** [spinupwp/spinupwp-plugin#41]
> I was wondering if it would be possible to add a feature to the SpinupWP plugin so that it purges the caches whenever a plugin, theme or core are updated? 
>
> I use ManageWP for running updates, so it would be great if the caches flushed automatically afterwards.

**Comment by tamal-sen** [comment]
I second this.. I am having a problem with caching too. It would be great if it purges the cache whenever a plugin, theme or core are updated along with any post/page update.

**Comment by gravnetic** [comment]
Third!

**Comment by katelynnbarlowe** [comment]
>It would be great if the SpinupWP plugin could hook into the `upgrader_process_complete` action that fires when plugins/themes/core are updated to automatically clear the caches.

https://community.spinupwp.com/c/suggestion-box/clear-caches-when-core-plugins-themes-are-updated
