### ISSUE TITLE
Implement wp_cache_*_multiple

### ISSUE THREAD

**Issue by spacedmonkey** [spinupwp/spinupwp-plugin#55]
Implement new functions, wp_cache_add_multiple, wp_cache_set_multiple and wp_cache_delete_multiple functions.

https://core.trac.wordpress.org/changeset/52700

**Comment by spacedmonkey** [comment]
https://make.wordpress.org/core/2022/04/29/caching-improvements-in-wordpress-6-0/

**Comment by A5hleyRich** [comment]
Resolved in a08dd6df4851fd135e4361de6e6f9450de57aed4

**Comment by A5hleyRich** [comment]
Thanks for raising this @spacedmonkey!
