### ISSUE TITLE
Update WP.org page to show SpinupWP instead of Delicious Brains under Contributors & Developers

### ISSUE THREAD

**Issue by bradt** [spinupwp/spinupwp-plugin#58]
<img width="968" alt="CleanShot 2022-06-11 at 17 55 02@2x" src="https://user-images.githubusercontent.com/190095/173204567-30c8b3be-1d4a-4f4e-9263-6ea5c1b07d91.png">

https://wordpress.org/plugins/spinupwp/

I believe we just need to update the `Contributors:` bit in the readme.txt to use `spinupwp` (the new WP.org account I just created) instead of `deliciousbrains`.

**Comment by A5hleyRich** [comment]
Done
