### ISSUE TITLE
PHP 8.1 compatibility 

### ISSUE THREAD

**Issue by afragen** [spinupwp/spinupwp-plugin#64]
In `Cache::delete()` I have seen occasions where the `$file` parameter is not defined. This results in a PHP warning in 8.1 and a fatal in 8.2. 

I do not know why this occurs but it does seem to happen. 

A simple update to the conditional solves the issues.

**Comment by Nicscott01** [comment]
This is the same issue I just documented: https://github.com/spinupwp/spinupwp-plugin/issues/72

Does it happen to you only when page cache is turned off in SpinupWP?

**Comment by Jamesclark32** [comment]
Resolved by #63
