### ISSUE TITLE
Increase timeout limits

### ISSUE THREAD

**Issue by Jamesclark32** [spinupwp/spinupwp-plugin#65]
The `timeout` and `read_timeout` values being set in `drop-ins/object-cache.php` on lines [602](https://github.com/spinupwp/spinupwp-plugin/blob/develop/drop-ins/object-cache.php#L602) and [603](https://github.com/spinupwp/spinupwp-plugin/blob/develop/drop-ins/object-cache.php#L603) are both very short at `1` second.

This can easily cause timeouts and errors as sites grow and purging their cache takes longer. 

These values should be increased to `5` seconds.

**Comment by jonathanhatch** [comment]
I was having trouble with some of my sites that are using Google SQL remotely not being able to flush the object cache. Changing the timeout values on lines 602 and 603 solve the problem for me. I bumped them both up to 30.

**Comment by georgefehr** [comment]
We're planning on an update for the plugin soon. In the meantime you can define the `WP_REDIS_TIMEOUT` and `WP_REDIS_READ_TIMEOUT` constants in your site's `wp-config.php` to configure the values. 

For example, to change the timeouts to 5s:
```php
define( 'WP_REDIS_TIMEOUT', 5 );
define( 'WP_REDIS_READ_TIMEOUT', 5 );
```

**Comment by brendon** [comment]
Thanks @georgefehr, we have about 120 sites, so individual changes like that are impractical for us :) Looking forward to the new version of the plugin :D
